sudo: required
language: java
jdk:
  - oraclejdk8
install:
#- git clone https://github.com/beowulfe/HAP-Java.git
#- cd HAP-Java
#- mvn install
- pwd
- cd ..
- rm -rf obera-base zwave
- git clone https://github.com/oberasoftware/obera-base.git
- cd obera-base && mvn -DskipTests install
- git clone https://github.com/comdata/zwave.git
- cd zwave && mvn -DskipTests install
- pwd
#- cd HomeAutomation

#sudo: false

cache:
  directories:
  - $HOME/.m2

addons:
  mariadb: '10.0'
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "homeautomation"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn install -DskipTests=true sonar:sonar org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

before_script:
  - mysql -u root -e 'CREATE DATABASE HA;'
  - mysql -u root HA < HomeAutomation/WebContent/WEB-INF/log4j.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)

