language: java
jdk:
  - oraclejdk8
#install:
#- git clone https://github.com/beowulfe/HAP-Java.git
#- cd HAP-Java
#- mvn install
#- cd ..

addons:
  mariadb: '10.0'
before_script:
  - mysql -u root -e 'CREATE DATABASE HA;'
after_success:
  - bash <(curl -s https://codecov.io/bash)
