language: java
jdk:
  - oraclejdk8
#install:
#- git clone https://github.com/beowulfe/HAP-Java.git
#- cd HAP-Java
#- mvn install
#- cd ..

sudo: false

addons:
  mariadb: '10.0'
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "HomeAutomation"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

before_script:
  - mysql -u root -e 'CREATE DATABASE HA;'
  - mysql -u root HA < HomeAutomation/WebContent/WEB-INF/log4j.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)

