site_name: HomeAutomation Documentation
site_description: Description of the HomeAutomation documentation
repo_url: https://github.com/comdata/HomeAutomation

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_css:
- css/extra.css
extra_javascript:
- js/extra.js

site_favicon: img/favicon.png

pages:
- Overview: 'index.md'
- English:
    - Home: 'en/index.md'
