CREATE TABLE LOGS
   (USER_ID VARCHAR(20)    NOT NULL,
    DATED   DATETIME(3)           NOT NULL,
    LOGGER  VARCHAR(255)    NOT NULL,
    LEVEL   VARCHAR(10)    NOT NULL,
    MESSAGE VARCHAR(8192)  NOT NULL
   );