CREATE TABLE LOGS
   (USER_ID VARCHAR(20)    NOT NULL,
    DATED   DATETIME(3)           NOT NULL,
    LOGGER  VARCHAR(255)    NOT NULL,
    LEVEL   VARCHAR(10)    NOT NULL,
    MESSAGE VARCHAR(8192)  NOT NULL
   );
   
DROP TABLE IF EXISTS `CONFIGURATIONSETTING`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `CONFIGURATIONSETTING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROPERTY` varchar(255) DEFAULT NULL,
  `SETTINGSGROUP` varchar(255) DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;   
   
insert into CONFIGURATIONSETTING ( PROPERTY , SETTINGSGROUP , VALUE ) values ('tvIp', 'tv', '127.0.0.1')